# Combine similar descriptors
#data.set$value[grep("attitude", data.set$value)] <- "attitudes"
#data.set$value[grep("behavior", data.set$value)] <- "behavior"
#data.set$value[grep("games", data.set$value)] <- "games"
#data.set$value[grep("knowledge ", data.set$value)] <- "knowledge"
#data.set$value[grep("science instruction", data.set$value)] <- "stem education"
#data.set$value[grep("mathematics instruction", data.set$value)] <- "stem education"
#data.set$value[grep("discussion", data.set$value)] <- "discussion"
#data.set$value[grep("scaffolding", data.set$value)] <- "scaffolding"
#data.set$value[grep("constructivism", data.set$value)] <- "constructivism"
#data.set$value[grep("lesson plans", data.set$value)] <- "instructional design"
#data.set$value[grep("instructional design", data.set$value)] <- "instructional design"
#data.set$value[grep("curriculum development", data.set$value)] <- "instructional design"
#data.set$value[grep("learning activities", data.set$value)] <- "instructional design"
#data.set$value[grep("video technology", data.set$value)] <- "specific technologies"
#data.set$value[grep("handheld devices", data.set$value)] <- "specific technologies"
#data.set$value[grep("faculty", data.set$value)] <- "teacher educators"
#data.set$value[grep("inquiry", data.set$value)] <- "stem education"
#data.set$value[grep("college school cooperation", data.set$value)] <- "field experiences"
#data.set$value[grep("field experience programs", data.set$value)] <- "field experiences"
#data.set$value[grep("student teaching", data.set$value)] <- "field experiences"
#data.set$value[grep("teaching skills", data.set$value)] <- "pedagogy"
#data.set$value[grep("teaching methods", data.set$value)] <- "pedagogy"

